### PR TITLE
Delete old commented out lines of code in div-alg.gi

### PR DESCRIPTION
**Pull request by drallenherman**
Delete old commented out lines of code in div-alg.gi

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
The actual change (https://github.com/gap-packages/wedderga/pull/74/commits/cfba3e655205d28a4f642d7d54904f752a2e96a4) looks OK - please change the base branch to `divalg`, fix the title of the PR, and then we need to wait for another round of Travis tests.

**Comment by olexandr-konovalov** [comment]
@drallenherman you also need to change the base branch. https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request explains what  the _base branch_ means: "the base branch is where changes should be applied, the head branch contains what you would like to be applied". Attached image shows where to select it.

Screenshot 2020-04-15 at 21 45 42

**Comment by drallenherman** [comment]
> @drallenherman you also need to change the base branch. https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request explains what the _base branch_ means: "the base branch is where changes should be applied, the head branch contains what you would like to be applied". Attached image shows where to select it.
> 
> Screenshot 2020-04-15 at 21 45 42

Ok.  I tried to do that on the website.

**Comment by olexandr-konovalov** [comment]
Merged. I don't know why there were three commits there (two identical with different commit IDs and then merge). When I did similar things before, I only had to change the base branch, and no extra commits appeared. But anyhow, tests pass, the cumulative diff was checked and looked OK, so I created a "squash commit" 6e1b9380f704212c5482400758ab45a671c4dc86 to keep the history clean. Thanks!

**Comment by olexandr-konovalov** [comment]
I also renamed the PR - we don't need the number, since it's displayed there anyway, and we usually use plain text descriptions (that may change from project to project, but that's our usual style).

**Pull request merged**
