### PR TITLE
Start collecting further tests for div-alg code

### PR DESCRIPTION
**Pull request by olexandr-konovalov**
Added `tst/div-alg.tst` and put there some examples from discussion in #64.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Increases coverage of div-alg.gi by 5.71%. Shall we merge this?

**Comment by olexandr-konovalov** [comment]
Added one more test - raises further from +5.71 to +5.82%. Shall I merge this, and then @angeldelriomateos and @drallenherman can rebase your branches to pick this up?

**Comment by drallenherman** [comment]
> Added one more test - raises further from +5.71 to +5.82%. Shall I merge this, and then @angeldelriomateos and @drallenherman can rebase your branches to pick this up?

sure.  does that mean we have to do a git pull then a makedoc.g and then git rebase?

**Comment by olexandr-konovalov** [comment]
Merged. This test is a "pure" test - it is not taken from the xml documentation and is much easier to handle therefore. I encourage you to add more examples to it to ensure good coverage standards for your PRs.

Now how to update your PRs depend on your setup.

@drallenherman for #67 do almost like we did earlier today: commit all changes, then
```
git checkout divalg
git pull
git checkout pr/65
git pull
git rebase divalg
git push origin -f
```
You can use rebase with `-i` option, to see which commits will be rebased, if you wish.

@angeldelriomateos for #64, because it is in your divalg, commit all changes, then do:
```
git checkout divalg
git pull origin divalg --rebase
git push angeldelriomateos divalg -f
```

**Pull request merged**
